name: Build and deploy JAR app to Azure Web App

env:
  AZURE_WEBAPP_NAME: ctam-dev-b001-webapp-service   # set this to your application's name
  # JAVA_VERSION: '17'                  # set this to the Java version to use
# Trigger test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  #   inputs:
  #     artifact-number:
  #       description: Specify the job run number as artifact number
  #       required: true
  #       type: string
      
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'  # or 'zulu', 'openjdk', etc.
          cache: maven
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ secrets.GITHUB_ACTOR }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
      - name: Build with Maven
        run: echo "mvn clean install"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app-${{ github.run_number }}
          path: '${{ github.workspace }}/Test.API.sln'

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app-${{ github.run_number }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        run: echo "Upload to az app service with publish profile"

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    environment: qa

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app-${{ github.run_number }}
          path: /

      - name: Do ls to check the Download artifact
        run: ls /
      # - name: Delete Previous builds
      #   uses