name: Build and deploy JAR app to Azure Web App

env:
  AZURE_WEBAPP_NAME: ctam-dev-b001-webapp-service   # set this to your application's name
  # JAVA_VERSION: '17'                  # set this to the Java version to use
# Trigger test
on:
  push:
    branches:
      - devops
  pull_request:
    branches:
      - devops
  workflow_dispatch:
  #   inputs:
  #     artifact-number:
  #       description: Specify the job run number as artifact number
  #       required: true
  #       type: string
      
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'  # or 'zulu', 'openjdk', etc.
          cache: maven
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ secrets.GITHUB_ACTOR }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app-${{ github.run_number }}
          path: '${{ github.workspace }}/target/*.jar'

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app-${{ github.run_number }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: <publishData><publishProfile profileName="ctam-dev-b001-webapp-service - Web Deploy" publishMethod="MSDeploy" publishUrl="ctam-dev-b001-webapp-service.scm.azurewebsites.net:443" msdeploySite="ctam-dev-b001-webapp-service" userName="$ctam-dev-b001-webapp-service" userPWD="oXzlcmmporeQBG2lqyZgRdqnXe9gnvNnrfgf1v7M6eHc0XqdoZl75ilsp2wX" destinationAppUrl="https://ctam-dev-b001-webapp-service.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="ctam-dev-b001-webapp-service - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-551.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="ctam-dev-b001-webapp-service\$ctam-dev-b001-webapp-service" userPWD="oXzlcmmporeQBG2lqyZgRdqnXe9gnvNnrfgf1v7M6eHc0XqdoZl75ilsp2wX" destinationAppUrl="https://ctam-dev-b001-webapp-service.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="ctam-dev-b001-webapp-service - Zip Deploy" publishMethod="ZipDeploy" publishUrl="ctam-dev-b001-webapp-service.scm.azurewebsites.net:443" userName="$ctam-dev-b001-webapp-service" userPWD="oXzlcmmporeQBG2lqyZgRdqnXe9gnvNnrfgf1v7M6eHc0XqdoZl75ilsp2wX" destinationAppUrl="https://ctam-dev-b001-webapp-service.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: '*.jar'

  deploy-qa:
    runs-on: self-hosted
    needs: build
    environment: qa

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app-${{ github.run_number }}
          path: ${{ env.var_name}}

      - name: Delete Previous builds
        uses